title: "Εν Ιορδάνη"
tagline: "κείμενα · σκέψεις · διαδρομές"
description: "Κείμενα και σκέψεις για επικαιρότητα, κοινωνία, πολιτική, ταξίδια και διαχρονικά ζητήματα."
about: >
  Ο άνθρωπος είναι ένα ανήσυχο πλάσμα.
  Ένα πλάσμα γεμάτο σκέψεις, φόβους, ιδέες, ανησυχίες. Ένα πλάσμα που έχει 
  την ανάγκη να εκφράζεται, να εκτονώνεται, να διοχετεύει την ενέργεια 
  των ανησυχιών του μέσω κάποιου καναλιού. Αυτή η σελίδα αποτελεί το δικό μου 
  κανάλι εκτόνωσης. Εδώ θα βρίσκουν χώρο σκέψεις, ιδέες, προτάσεις, 
  σχολιασμοί της επικαιρότητας και όχι μόνο. Εδώ θα γίνεται μια προσπάθεια 
  ανάλυσης της πραγματικότητας που μας περιβάλλει μέσα από τα δικά μου μάτια, 
  άλλοτε με σοβαρό και άλλοτε με σαρκαστικό τρόπο. Θα υπάρχουν περιγραφές 
  εξορμήσεων σε γνωστά και άγνωστα μέρη, αλλά και πολλά άλλα…
  Ένα ποτ-πουρί. Μία κατάσταση «τα πάντα-όλα», που θα καθρεφτίζει και 
  θα αντανακλά εμένα: τις σκέψεις, τους φόβους, τις ιδέες, τις ανησυχίες μου. 
  Ο άνθρωπος είναι ένα ανήσυχο πλάσμα.
url: "https://a-thrax.gr"
baseurl: ""
lang: el
theme: null
logo: /assets/social-image.jpg

defaults:
  - scope:
      path: ""
    values:
      image: /assets/social-image.jpg

permalink: /:year-:month-:day-:title.html

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - template
  - README.md
  - HOW-TO-ADD-AN-ARTICLE.md
  - new-article-template.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
